version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sample-cognito"
region = "us-east-1"
s3_bucket="sam-cc-bucket"
s3_prefix="sam_deploy"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
[default.deploy.parameters]
stack_name = "manna"
resolve_s3 = true
s3_prefix = "manna"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"dev\""
image_repositories = []
