name: Deploy Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::992382613321:role/OIDCrole
        aws-region: us-east-1
        role-session-name: GitHubActions
        audience: sts.amazonaws.com

    - name: Set up AWS Session
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
        aws sso login --profile github-actions

    - name: Deploy Lambda
      run: |
        sam init
        sam build --template-file lambda-template.yaml
        sam deploy --template-file lambda-template.yaml
